language: node_js
node_js:
- node
after_script: npm run coveralls
deploy:
  provider: npm
  email: hello@marcbizal.com
  api_key:
    secure: tvAeKVUgmTr0y9/0CfoLw2tYB1BmxY/Yckyjolpkwh6+P/rsW80wgeN6ewS8c2/PSpKryTEHBy17ixej4KKnJk2bc188Kb/i2cJAPWauXCx1Z0PBwvd8eQlWREGvAhmZdoiqI/ddOCGkDx2Rfu0B5w4y00wEi86i8bKmII50Zj9BmV3aNYPWYAMb95ctrhdcMDiXYF9dNyetxj3XJMPN2zG42KoBt2AwKbvxGidYA0C3CFy5//JOJjkP8ub9nwZVxmdiMigez8p6j2Y/T7sIeoJzsrtSI8uRvSrX308mHVsToScqBWXHudMKfiQcgFvh+wkvV73ti+119GeKBzy0mI9P7aeE1SP5GTxrD0Bbcj5QtCMnob5WpZq0NOF1V7FbrGmND9vUNngjarBLitjc6wqcXUzQVIM/z4K4zQZRaQEK1ixHPrMQL47VGcDcnHw8fqdjHwJqICb+99isAhFnAgT12+bQetMfFQzejFqXATV5UtLfrXFjAhlbJPqIZTBL+mYT+MN8j0ecL/t60ZnkktSi7dTtOxJXiYEBOlA6cq/GgljZB07NAfiZ72VtG7ehN/6kuxjDL+qnaabJPAK8didbQas7H4LNtOz7negDrJaBa/Bs/Oq0uYuCTTUx6JnY+QKMjcPxwvLm0aUi0lfoD13jt+xqokoCc25PmVksEx0=
  on:
    tags: true
    repo: marcbizal/lwo-parser
